repository:
	wget -O /tmp/endpoint-repo-1.7-1.x86_64.rpm https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
	sudo yum localinstall -y /tmp/endpoint-repo-1.7-1.x86_64.rpm

.PHONY: repository
